on: pull_request

name: Fluent-linter
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: fluent_linter_action
        uses: calyptia/fluent-linter-action@main
        with:
          calyptia-api-key: ${{ secrets.CALYPTIA_API_KEY }}
          follow-symbolic-links: 'true' # this is optional. It defaults to false.
          config-location-glob: 'fluent-bit.conf'
